### ISSUE TITLE
I Use MongoDB But Get Error in FilterCharacters() Method

### ISSUE THREAD

**Issue by j-ghadiri** [tpeczek/Demo.AspNetCore.JqGrid#1]
When using Mono Database
The FilterCharacters method for queries generates the following error

 ` Unsupported filter: Invoke(value(System.Func`2[App.Core.Collection.User.ApplicationUser,System.Boolean]), {document}).`

because [“Unsupported filter” using in Mongo 2.x driver](http://www.codewrecks.com/blog/index.php/2016/04/26/unsupported-filter-using-containsany-in-mongo-2-x-driver/)

**Comment by tpeczek** [comment]
Hi @j-ghadiri,

I'm afraid I'm not sure what you are asking for. If I have understood correctly you are attempting to migrate this demo project to use MongoDB and you have hit a MongoDB driver specific issue.

If you have ready to use repro somewhere (I don't see it in you repository) I can try to help, but it doesn't seem to be in any way related to jqGrid itself.
