### ISSUE TITLE
Migrate to ASP.NET Core 3.0

### ISSUE THREAD

**Issue by tpeczek** [tpeczek/Demo.AspNetCore.JqGrid#2]

**Comment by j-ghadiri** [comment]
Hello Mr. Tomasz Pęczek
how to upgrade this sample for ASP.NET Core 3.0 or ASP.NET Core 3.1

**Comment by j-ghadiri** [comment]
Hello Mr. Tomasz Pęczek
I update Lib.AspNetCore.Mvc.JqGrid for supporting .Net Core 3.1
With Sample Demo
I Hope it will be useful

[AspNetCore.JqGrid-master.core3.1.zip](https://github.com/tpeczek/Lib.AspNetCore.Mvc.JqGrid/files/3965091/AspNetCore.JqGrid-master.core3.1.zip)

**Comment by tpeczek** [comment]
Hi @j-ghadiri 

As you have already figured out, it requires upgrading Lib.AspNetCore.Mvc. Unfortunately this is not as easy as it sounds as the default JSON serialization/deserialization needs to be rewritten to use `System.Text.Json` and make the current Newtonsoft.Json-based implementation an additional one. This will cause new version to be no backward compatible, so I want to use that opportunity to clean up some staff and drop 1.x.y entirely while keeping 2.x.y at least as maintained line. This requires some work, but I'm still hoping to get all of this done in December.
