### ISSUE TITLE
No data available to view into the jQuery Grid.

### ISSUE THREAD

**Issue by Ajit666** [tpeczek/Demo.AspNetCore.JqGrid#3]
Nothing is showing here except the content of the _Layout.cshtml file.

**Comment by tpeczek** [comment]
I need something more to go with.

Just in case I've just downloaded and run fresh copy of demo application and it seems to be working as expected. You should have some logs (if you are running the project directly, they are most likely outputted to the console window where ASP.NET Core process is running).

**Comment by nareshkumarhk** [comment]
Just downloaded the sample code base, how to get it to work. as mentioned above its just loading the _Layout.cshtml.

**Comment by tpeczek** [comment]
I really don't know what might be happening. I'm able to download a clean copy, open in VS, and run without any issues.

Do you have anything logged either in ASP.NET Core console or in browser console?
