### ISSUE TITLE
Add DateTime Field and DropDown With Data From Related Source to Demos

### ISSUE THREAD

**Issue by malathip72** [tpeczek/Demo.AspNetCore.JqGrid#4]
Please add demo tutorial on this recent project. The project does not include
date type and dropdown list with data from related table. Please add the two features.

**Comment by tpeczek** [comment]
What context do you have in mind for that DropDown with data from related table (Cell Editing, Inline Editing, Form Editing, etc.)?

**Comment by tpeczek** [comment]
Samples has been extended with a DateTime field.

I need to take a break from this to take care of somethign else, so the Planets for Characters will have to wait (probably I'll start working on it next week).

**Comment by tpeczek** [comment]
I was looking at finishing this one, but I still need an explanation about what you expect as "DropDown with data from related table" sample.
