### ISSUE TITLE
Sample Project is not Running.. Getting 404 Java script files there is no lib folder exist

### ISSUE THREAD

**Issue by naveenkv66** [tpeczek/Demo.AspNetCore.JqGrid#5]

**Comment by tpeczek** [comment]
Which version of Visual Studio (or maybe some other tooling) are you using?

The lib folder is generated by Bower (you should see `bower.json` file in the project) which used to work out-of-the-box in Visual Studio prior to Visual Studio 2017. In later versions it requires some manual work.

I guess I should bite the bullet and finally migrate to LibMan.
